spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useSSL=false
    #url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
    #dirverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8
    initialization-mode: always
  redis:
    host: localhost
    port: 6379

#logger
logging:
  level:
    ROOT: WARN
    org.springframework: INFO
    com.genkaipg: DEBUG

  pattern:
    console:  "%date %level [%thread] [%file:%line %method] %msg%n"
    file:   "%date %level [%thread] %logger{32} [%file:%line %method] %msg%n"
